### ISSUE TITLE
”/home/user/s2e/source/guest-images//scripts/get_iso.sh: jigdo-lite: not found“ while building image

### ISSUE THREAD

**Issue by beraphin** [S2E/s2e-env#134] opened 2018-05-15 07:33 UTC
Hi,
    I've pulled  cyberhaven/s2e image on docker and started to study how to build s2e environment and how to use s2e.
    But the process of building s2e environment is very painful for me, and I don't know if I did anything wrong. I was building s2e environment according to https://github.com/S2E/docs/blob/master/src/s2e-env.rst step by step, and I've got following issues:

1. While running "s2e init" and  "s2e build" commands need root privileges, running "s2e image_build" got error cause it cannot be running under root, and there is just one root account on cyberhaven/s2e, it does not make any sense, and I have to add an user manually，and add permissions for this account to access those s2e files;

2. I've got another error when running "s2e image_build", it turned out that it stuck in 
`git clone git://sourceware.org/git/systemtap.git`
It always time out, I cannot download systemtap by git even using proxy for no reason. I don't know if it is my problem, so I have to upload systemtap to my github and change the link in source/guest-images/Linux/docker/Dockerfile.x86_64, and it worked;

3. After solving first 2 issues, I've got the 3rd. But I've found the same issue at https://github.com/S2E/s2e-env/issues/49, according to this I changed $HOME and it worked for me. Maybe it will be better if not to rely on $HOME for run-docker.sh;

4. The last one, and this is why I post this issue, after solving the problems above , I have got the following error while running "s2e image_build":
```
s2e@0898c35098cb:/home/user/s2e$ s2e image_build debian-9.2.1-x86_64
[Tue May 15 07:25:24 UTC 2018] [/home/user/s2e/images/.tmp-output/debian-9.2.1-x86_64/debian-9.2.1-x86_64.iso] Downloading disk image...
cd /home/user/s2e/images/.tmp-output/debian-9.2.1-x86_64 && /home/user/s2e/source/guest-images//scripts/get_iso.sh https://cdimage.debian.org/cdimage/archive/9.2.1/amd64/jigdo-cd/debian-9.2.1-amd64-netinst.jigdo /home/user/s2e/images/.tmp-output/debian-9.2.1-x86_64/debian-9.2.1-x86_64.iso
https://cdimage.debian.org/cdimage/archive/9.2.1/amd64/jigdo-cd/debian-9.2.1-amd64-netinst.jigdo /home/user/s2e/images/.tmp-output/debian-9.2.1-x86_64/debian-9.2.1-x86_64.iso
Downloading https://cdimage.debian.org/cdimage/archive/9.2.1/amd64/jigdo-cd/debian-9.2.1-amd64-netinst.jigdo to debian-9.2.1-amd64-netinst.jigdo
--2018-05-15 07:25:24--  https://cdimage.debian.org/cdimage/archive/9.2.1/amd64/jigdo-cd/debian-9.2.1-amd64-netinst.jigdo
Connecting to 127.0.0.1:8118... connected.
Proxy request sent, awaiting response... 200 OK
Length: 26184 (26K)
Saving to: 'debian-9.2.1-amd64-netinst.jigdo'

debian-9.2.1-amd64-netinst.jigdo                100%[====================================================================================================>]  25.57K  69.4KB/s    in 0.4s

2018-05-15 07:25:28 (69.4 KB/s) - 'debian-9.2.1-amd64-netinst.jigdo' saved [26184/26184]

Downloading https://cdimage.debian.org/cdimage/archive/9.2.1/amd64/jigdo-cd/debian-9.2.1-amd64-netinst.template to debian-9.2.1-amd64-netinst.template
--2018-05-15 07:25:28--  https://cdimage.debian.org/cdimage/archive/9.2.1/amd64/jigdo-cd/debian-9.2.1-amd64-netinst.template
Connecting to 127.0.0.1:8118... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3521819 (3.4M)
Saving to: 'debian-9.2.1-amd64-netinst.template'

debian-9.2.1-amd64-netinst.template             100%[====================================================================================================>]   3.36M   788KB/s    in 4.4s

2018-05-15 07:25:35 (788 KB/s) - 'debian-9.2.1-amd64-netinst.template' saved [3521819/3521819]

/home/user/s2e/source/guest-images//scripts/get_iso.sh: 71: /home/user/s2e/source/guest-images//scripts/get_iso.sh: jigdo-lite: not found
/home/user/s2e/source/guest-images//Makefile.linux:184: recipe for target '/home/user/s2e/images/.tmp-output/debian-9.2.1-x86_64/debian-9.2.1-x86_64.iso' failed
make: *** [/home/user/s2e/images/.tmp-output/debian-9.2.1-x86_64/debian-9.2.1-x86_64.iso] Error 127
ERROR: [image_build] Image build failed
```

I am suprised that I have got so many problems while building s2e in cyberhaven/s2e, I thought it would be easy using docker. I don't know if I missed any import things in tutorial, or maybe they are bugs in s2e project?

Thanks

**Comment by adrianherrera** [comment] 2018-05-15 07:39
For the last error, it seems that you do not have the necessary package installed. When you ran `s2e init` it should have installed the `jigdo-file` package (see https://github.com/S2E/s2e-env/blob/master/s2e_env/dat/config.yaml#L51), which gives you the `jigdo-lite` command. Please check that this package is installed.

For the other comments, `s2e build` should not require root privileges. Are you sure that this is the case? If you used `s2e init` to create the environment and then switched to another user, then yes, you would have had permission issues running `s2e build`. But this is a standard permission thing.

The only time you need root privileges is to install the packages during the `init` stage. If you are having to switch users, then yes, you will have permission issues in your S2E environment. Perhaps I need to think of a clearer way for this, because I've had a few people do this. Any suggestions are welcome!

Please let me know if this solves your problems!

**Comment by adrianherrera** [comment] 2018-05-15 07:43
P.S. I can `git clone git://sourceware.org/git/systemtap.git` fine, so perhaps sourceware was done for a little bit.

**Comment by beraphin** [comment] 2018-05-15 09:28
@adrianherrera 
Thanks, after installing `jindog-file` this problem was solved. And after building for long time, I've got following error:
```
s2e@0898c35098cb:/home/user/s2e$ s2e image_build debian-9.2.1-x86_64
[Tue May 15 09:25:33 UTC 2018] [/home/user/s2e/images/output/debian-9.2.1-x86_64/image.raw.s2e.ready] Creating snapshot...
LD_PRELOAD=/home/user/s2e/install/share/libs2e/libs2e-x86_64.so /home/user/s2e/install/bin/qemu-system-x86_64 -enable-kvm -drive if=ide,index=0,file=/home/user/s2e/images/output/debian-9.2.1-x86_64/image.raw.s2e,format=s2e,cache=writeback -serial file:/home/user/s2e/images/output/debian-9.2.1-x86_64/serial_ready.txt -enable-serial-commands -net none -net nic,model=e1000  -m 256M
Starting libs2e...
Opening /dev/kvm
Warning: vlan 0 is not connected to host network
Could not initialize SDL(No available video device) - exiting
/home/user/s2e/source/guest-images//Makefile.linux:203: recipe for target '/home/user/s2e/images/output/debian-9.2.1-x86_64/image.raw.s2e.ready' failed
make: *** [/home/user/s2e/images/output/debian-9.2.1-x86_64/image.raw.s2e.ready] Error 1
ERROR: [image_build] Image build failed

```

**Comment by vitalych** [comment] 2018-05-15 09:48
The problem is "Could not initialize SDL(No available video device) - exiting".
This is strange, image building should be headless by default unless you pass -g to s2e image_build.
Perhaps you have a stale GRAPHICS env variable (you would have to unset it).

**Comment by vitalych** [comment] 2018-05-15 09:50
As for system tap issue, perhaps if we fork its repo into github, it will be more reliable.

**Comment by vitalych** [comment] 2018-05-15 09:57
@adrianherrera I think s2e-env should forbid running itself as root by default (and provide a flag to override this if needed).

**Comment by beraphin** [comment] 2018-05-15 10:46
@vitalych 
Thanks for your reply, and I added `-nographic`  in `TAKE_SNAPSHOT` function then it gave a qemu commandline:
```
s2e@0898c35098cb:/home/user/s2e$ s2e image_build debian-9.2.1-x86_64
[Tue May 15 10:32:48 UTC 2018] [/home/user/s2e/images/output/debian-9.2.1-x86_64/image.raw.s2e.ready] Creating snapshot...
LD_PRELOAD=/home/user/s2e/install/share/libs2e/libs2e-x86_64.so /home/user/s2e/install/bin/qemu-system-x86_64 -enable-kvm -drive if=ide,index=0,file=/home/user/s2e/images/output/debian-9.2.1-x86_64/image.raw.s2e,format=s2e,cache=writeback -serial file:/home/user/s2e/images/output/debian-9.2.1-x86_64/serial_ready.txt -enable-serial-commands -net none -net nic,model=e1000  -m 256M  -nographic
Starting libs2e...
Opening /dev/kvm
QEMU 1.0.50 monitor - type 'help' for more information
(qemu) Warning: vlan 0 is not connected to host network
(qemu) quit
s2e-block: dirty sectors on close:0
[Tue May 15 10:36:50 UTC 2018] [/home/user/s2e/images/output/debian-9.2.1-x86_64/image.json] Creating image descriptor...
/home/user/s2e/source/guest-images//scripts/generate_image_descriptor.py -i /home/user/s2e/source/guest-images//images.json -o /home/user/s2e/images/output/debian-9.2.1-x86_64/image.json -n "debian-9.2.1-x86_64" snapshot="ready" qemu_build="x86_64" memory="256M" qemu_extra_flags="-net none -net nic,model=e1000 "
INFO: [image_build] Built image 'debian-9.2.1-x86_64'
```
I have to quit it manually, but I do not know if it's right.
it seems the image is built successful.
But after I running the following commandline, it seems the path is not correct:
```
s2e@0898c35098cb:/home/user/s2e$ s2e new_project --image debian-9.2.1-x86_64 /bin/ls
ERROR: [new_project] Unable to open image description /home/user/s2e/images/debian-9.2.1-x86_64/image.json
Check that the image exists
s2e@0898c35098cb:/home/user/s2e$ ls -la ./images/
total 20
drwxrwxrwx 1 root root 4096 May 15 08:34 .
drwxrwxrwx 1 root root 4096 May 15 10:32 ..
drwxrwxr-x 2 s2e  s2e  4096 May 15 06:10 .stamps
drwxrwxr-x 4 s2e  s2e  4096 May 15 06:04 .tmp-output
drwxrwxr-x 3 s2e  s2e  4096 May 15 08:34 output
s2e@0898c35098cb:/home/user/s2e$ find -name debian-9.2.1-x86_64
./images/.tmp-output/debian-9.2.1-x86_64
./images/output/debian-9.2.1-x86_64
s2e@0898c35098cb:/home/user/s2e$ ls -la ./images/output/debian-9.2.1-x86_64/
guestfs/          image.json        image.raw.s2e     imagefs/          serial_ready.txt

```
The target image is not under image/, but under image/output/, is that right?

**Comment by vitalych** [comment] 2018-05-15 11:32
The should be at the root. Something is wrong with the environment variables that control image building.
They should be overriden by s2e image_build.
https://github.com/S2E/guest-images/blob/master/Makefile.common#L38
https://github.com/S2E/s2e-env/blob/master/s2e_env/commands/image_build.py#L374

Perhaps you could invoke s2e image_build like this to have more debug output:
```
S2EENV_LOG_LEVEL=DEBUG s2e image_build debian-9.2.1-x86_64
```

**Comment by beraphin** [comment] 2018-05-15 12:12
Well, in `cyberhaven/s2e`  using `print` instead of `logging`, may because it used old version of `s2e_env`. And I'm wondering how could they be at the root since we run `image_build` under non-root account?

**Comment by adrianherrera** [comment] 2018-05-15 12:19
The root `images` directory, not root account. The image should appear in `/home/user/s2e/images`.

What do you mean by `cyberhaven/s2e`?

**Comment by beraphin** [comment] 2018-05-15 12:54
Yeah, I am trying to use the newest s2e_env to see if it would be better

**Comment by vitalych** [comment] 2018-05-15 12:56
The docker image should already contain the latest s2e-env. I update it every time major PRs are merged.

**Comment by beraphin** [comment] 2018-05-15 13:04
Do you mean this one?
https://hub.docker.com/r/cyberhaven/s2e/tags/
It was updated 1 year ago

**Comment by vitalych** [comment] 2018-05-15 13:09
This is the demo docker image, updated 17 days ago: https://hub.docker.com/r/cyberhaven/s2e-demo/
cyberhaven/s2e is an intermediate build step of the s2e-demo docker image, I must have pushed it by mistake. I'll delete it. Sorry for the confusion.

**Comment by beraphin** [comment] 2018-05-15 13:13
Wow I have seen this docker too, and wondered which one to use. It seems I've got a bad luck.
Thanks for help.

**Comment by beraphin** [comment] 2018-05-16 01:45
Hi, I have one last question. If I want to build s2e inside cyberhaven/s2e-demo image, what tutorial should I read?
[](https://github.com/S2E/docs/blob/master/src/BuildingS2E.rst#building-s2e-manually
)
[](https://github.com/S2E/docs/blob/master/src/s2e-env.rst)

**Comment by beraphin** [comment] 2018-05-16 06:02
Hi
I am trying to build s2e inside `cyberhaven/s2e-demo` image(don't know if it's possible), and when running `s2e image_build debian-9.2.1-x86_64`, it stopped at `waiting for unfinished jobs`:
```
s2e@88f939178454:~/s2e$ s2e image_build debian-9.2.1-x86_64
INFO: [image_build] The following images will be built:
INFO: [image_build]  * debian-9.2.1-x86_64
INFO: [image_build] Kernel repository already exists in /home/s2e/s2e/source/s2e-linux-kernel
WARNING: [image_build] Image creation will run in headless mode. Use --gui to see graphic output for debugging
make: Entering directory '/home/s2e/s2e/images'
rm -Rf /home/s2e/s2e/images/debian-9.2.1-x86_64/guestfs && mkdir -p /home/s2e/s2e/images/debian-9.2.1-x86_64/guestfs
[Wed May 16 05:58:37 UTC 2018] [/home/s2e/s2e/images/debian-9.2.1-x86_64/image.raw.s2e.ready] Creating snapshot...
LD_PRELOAD=/home/s2e/s2e/install/share/libs2e/libs2e-x86_64.so /home/s2e/s2e/install/bin/qemu-system-x86_64 -enable-kvm -drive if=ide,index=0,file=/home/s2e/s2e/images/debian-9.2.1-x86_64/image.raw.s2e,format=s2e,cache=writeback -serial file:/home/s2e/s2e/images/debian-9.2.1-x86_64/serial_ready.txt -enable-serial-commands -net none -net nic,model=e1000  -m 256M -nographic -monitor null
[Wed May 16 05:58:37 UTC 2018] [debian-9.2.1-x86_64] Extracting guestfs...
fusermount -u /home/s2e/s2e/images/debian-9.2.1-x86_64/imagefs
fusermount: entry for /home/s2e/s2e/images/debian-9.2.1-x86_64/imagefs not found in /etc/mtab
/home/s2e/s2e/source/guest-images//Makefile.linux:202: recipe for target '/home/s2e/s2e/images/debian-9.2.1-x86_64/guestfs' failed
make: [/home/s2e/s2e/images/debian-9.2.1-x86_64/guestfs] Error 1 (ignored)
mkdir -p /home/s2e/s2e/images/debian-9.2.1-x86_64/imagefs
# TODO: rsync only executable files
cd /home/s2e/s2e/images/debian-9.2.1-x86_64 && trap 'fusermount -u imagefs && rmdir imagefs' EXIT && guestmount --ro -i -a image.raw.s2e imagefs && rsync --links -rt --exclude '*.deb' imagefs/* guestfs
Starting libs2e...
Opening /dev/kvm
Warning: vlan 0 is not connected to host network
libguestfs: trace: set_verbose true
libguestfs: trace: set_verbose = 0
libguestfs: create: flags = 0, handle = 0x63e8b0, program = guestmount
libguestfs: trace: set_recovery_proc false
libguestfs: trace: set_recovery_proc = 0
libguestfs: trace: add_drive "image.raw.s2e" "readonly:true"
libguestfs: creating COW overlay to protect original drive content
libguestfs: trace: get_tmpdir
libguestfs: trace: get_tmpdir = "/tmp"
libguestfs: trace: disk_create "/tmp/libguestfs3aOVpZ/overlay1" "qcow2" -1 "backingfile:/home/s2e/s2e/images/debian-9.2.1-x86_64/image.raw.s2e"
libguestfs: command: run: qemu-img
libguestfs: command: run: \ create
libguestfs: command: run: \ -f qcow2
libguestfs: command: run: \ -o backing_file=/home/s2e/s2e/images/debian-9.2.1-x86_64/image.raw.s2e
libguestfs: command: run: \ /tmp/libguestfs3aOVpZ/overlay1
Formatting '/tmp/libguestfs3aOVpZ/overlay1', fmt=qcow2 size=4294967296 backing_file=/home/s2e/s2e/images/debian-9.2.1-x86_64/image.raw.s2e encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
libguestfs: trace: disk_create = 0
libguestfs: trace: add_drive = 0
libguestfs: trace: launch
libguestfs: trace: version
libguestfs: trace: version = <struct guestfs_version *>
libguestfs: trace: get_backend
libguestfs: trace: get_backend = "direct"
libguestfs: launch: program=guestmount
libguestfs: launch: version=1.32.2
libguestfs: launch: backend registered: unix
libguestfs: launch: backend registered: uml
libguestfs: launch: backend registered: libvirt
libguestfs: launch: backend registered: direct
libguestfs: launch: backend=direct
libguestfs: launch: tmpdir=/tmp/libguestfs3aOVpZ
libguestfs: launch: umask=0002
libguestfs: launch: euid=1000
libguestfs: trace: get_backend_setting "force_tcg"
libguestfs: trace: get_backend_setting = NULL (error)
libguestfs: trace: get_cachedir
libguestfs: trace: get_cachedir = "/var/tmp"
libguestfs: [00000ms] begin building supermin appliance
libguestfs: [00000ms] run supermin
libguestfs: command: run: /usr/bin/supermin
libguestfs: command: run: \ --build
libguestfs: command: run: \ --verbose
libguestfs: command: run: \ --if-newer
libguestfs: command: run: \ --lock /var/tmp/.guestfs-1000/lock
libguestfs: command: run: \ --copy-kernel
libguestfs: command: run: \ -f ext2
libguestfs: command: run: \ --host-cpu x86_64
libguestfs: command: run: \ /usr/lib/x86_64-linux-gnu/guestfs/supermin.d
libguestfs: command: run: \ -o /var/tmp/.guestfs-1000/appliance.d
supermin: version: 5.1.14
supermin: package handler: debian/dpkg
supermin: acquiring lock on /var/tmp/.guestfs-1000/lock
supermin: build: /usr/lib/x86_64-linux-gnu/guestfs/supermin.d
supermin: reading the supermin appliance
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/base.tar.gz type gzip base image (tar)
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/daemon.tar.gz type gzip base image (tar)
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/excludefiles type uncompressed excludefiles
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/hostfiles type uncompressed hostfiles
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/init.tar.gz type gzip base image (tar)
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages-hfsplus type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages-reiserfs type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/packages-xfs type uncompressed packages
supermin: build: visiting /usr/lib/x86_64-linux-gnu/guestfs/supermin.d/udev-rules.tar.gz type gzip base image (tar)
supermin: mapping package names to installed packages
supermin: resolving full list of package dependencies
supermin: build: 196 packages, including dependencies
supermin: build: 6870 files
supermin: build: 3793 files, after matching excludefiles
supermin: build: 3802 files, after adding hostfiles
supermin: build: 3802 files, after removing unreadable files
supermin: build: 3806 files, after munging
supermin: failed to find a suitable kernel (host_cpu=x86_64).

I looked for kernels in /boot and modules in /lib/modules.

If this is a Xen guest, and you only have Xen domU kernels
installed, try installing a fullvirt kernel (only for
supermin use, you shouldn't boot the Xen guest with it).
libguestfs: error: /usr/bin/supermin exited with error status 1, see debug messages above
libguestfs: trace: launch = -1 (error)
libguestfs: trace: close
libguestfs: closing guestfs handle 0x63e8b0 (state 0)
libguestfs: command: run: rm
libguestfs: command: run: \ -rf /tmp/libguestfs3aOVpZ
fusermount: entry for /home/s2e/s2e/images/debian-9.2.1-x86_64/imagefs not found in /etc/mtab
/home/s2e/s2e/source/guest-images//Makefile.linux:202: recipe for target '/home/s2e/s2e/images/debian-9.2.1-x86_64/guestfs' failed
make: *** [/home/s2e/s2e/images/debian-9.2.1-x86_64/guestfs] Error 1
make: *** Waiting for unfinished jobs....
```

**Closed** 2018-05-16 07:49 UTC
