### ISSUE TITLE
guest-images: no module named jinja2 thrown by get_setting.py

### ISSUE THREAD

**Issue by tashfia-r** [S2E/s2e-env#358] opened 2019-12-16 04:55 UTC
Hi, after s2e build ran successfully, I tried to build the linux images. But a warning is shown like -
File "/home/user/s2e/source/guest-images//scripts/get_setting.py", line 28, in <module>
    import jinja2
ImportError: No module named jinja2
and at last the image build failed showing -
ERROR: [image_build] 

  RAN: /usr/bin/make --directory=/home/user/s2e/images --file=/home/user/s2e/source/guest-images/Makefile -j 2 debian-9.2.1-i386

  STDOUT:

  STDERR:

Can I manulay change the script get_setting.py so that no import error occurs or another issue is happening? Please help.

**Comment by vitalych** [comment] 2019-12-16 19:00
This is odd, jinja2 should be installed, it's a listed requirement for s2e-env. Did you activate virtual env properly?

**Comment by tashfia-r** [comment] 2019-12-16 19:07
Yes. At first I installed the dependencies and then followed the s2e doc. I activated venv at the first place.

**Comment by vitalych** [comment] 2019-12-16 19:09
Could you install jinja2 system wide? Maybe the script doesn't run within the venv somehow.

**Comment by tashfia-r** [comment] 2019-12-16 19:11
Ok. let me try

**Comment by tashfia-r** [comment] 2019-12-16 19:14
do I have to build again?

**Comment by vitalych** [comment] 2019-12-16 19:15
You can run image_build again.

**Comment by vitalych** [comment] 2019-12-16 19:16
If it still doesn't work, you can download pre-built images instead.

**Comment by tashfia-r** [comment] 2019-12-16 19:18
I ran image_build. It is still showing the same. How can I download pre-built images?

**Comment by vitalych** [comment] 2019-12-16 19:19
`s2e image_build -d ...`

**Comment by tashfia-r** [comment] 2019-12-16 19:45
Thanks. But it won't create any issue during running analysis?

**Comment by vitalych** [comment] 2019-12-16 19:46
No, it shouldn't

**Comment by LalaNguyen** [comment] 2020-02-13 06:23
Hi, I came across this issue as well. The problem is because get_setting.py will run with python3 whereas original venv environment uses python2. Python3 won't see the jinja2 because it was installed for python2. You can test the venv environment with python3 and see whether the jinja2 is installed. My solution is to install pip3 and then install the missing jinja2.

**Comment by vitalych** [comment] 2020-02-13 10:26
We have just upgraded s2e-env to python3.
https://groups.google.com/forum/#!topic/s2e-dev/LZOHAAk9nqI
Does this solve the issue?

**Comment by LalaNguyen** [comment] 2020-02-13 10:44
oh, pardon me I did not catch the above message. I think it should be alright. Thanks for your help! :)

**Comment by vitalych** [comment] 2020-02-13 10:52
No problem, feel free to close this issue if it works

**Comment by LalaNguyen** [comment] 2020-02-14 06:30
Hi vitalych,

The issue is gone for good :). Thanks you for your helps! Unfortunately, I do not have permission to close this repo, so I will leave this to the owner.

**Closed** 2020-02-14 10:08 UTC
